// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ButtonBar: typeof import('./src/components/bar/ButtonBar.vue')['default']
    CustomBlock: typeof import('./src/components/CustomBlock.vue')['default']
    FlexBox: typeof import('./src/components/box/FlexBox.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyCode: typeof import('./src/components/MyCode.vue')['default']
    MyDoc: typeof import('./src/components/MyDoc.vue')['default']
    MyDocSection: typeof import('./src/components/MyDocSection.vue')['default']
    MyDocSectionItem: typeof import('./src/components/MyDocSectionItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
